### ISSUE TITLE
✨ Admin Portal > Tally results: results report improvments (Rollback)

### ISSUE THREAD

**Issue by Galb-moveo** [sequentech/step#1101]
### Preflight checklist

- [ ] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

1- need to remove the blan and invalid explicit votes from the list of candidates in the results, in both the web results and reports, just hide this answer/candidate with type Invalid vote or bllank vote

2- add result template in Spanish that can be configured when executing the tally

### Screenshots/videos Before

<empty>

### Report After Implementation

![Image](https://github.com/user-attachments/assets/50cdbde1-13fb-4f00-baac-4e571d4c5150)

### Screenshots/videos after Implementation

![Image](https://github.com/user-attachments/assets/2a4c2ac2-09b6-4f67-8c47-3b6f0adb763c)

<empty>

```[tasklist]
# Tasks
- [x] remove the blan and invalid explicit votes from the list of candidates in the results
- [x] add result template in Spanish that can be configured when executing the tally
- [ ] Apply changes to main
```

```[tasklist]
# Main PRs
- [ ] TODO
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/step/pull/1103
- [ ] https://github.com/sequentech/step/pull/1121
- [ ] https://github.com/sequentech/step/pull/1126
```

### Attached files

[report_content_es.html.zip](https://github.com/user-attachments/files/17774169/report_content_es.html.zip)
