### ISSUE TITLE
✨ Improve cryptographic soundness

### ISSUE THREAD

**Issue by ruescasd** [sequentech/step#46]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

✨ Improve cryptographic soundness

### Tasks

```[tasklist]
# Tasks
- [x] Generating independent generators - RUG
- [x] Generating independent generators - Ristretto
- [ ] Review generator implementations
- [ ] Generators are not compared between proof and verification, only regenerated from seed
- [ ] Fiat Shamir transforms
- [ ] Source of randomness
- [ ] Hashing to Integer (HashTo, rug backend) with only 512 bits using mod
- [ ] Shuffle verify, check for identical ciphertexts (no permutation and/or no re-encryption)
- [ ] Not checking for duplicates in incoming ciphertexts (Weeding)
- [ ] Check proof of plaintext knowledge in the mixnet (as well as ballotbox)
- [ ] Generators_fips not checking quadratic residuousity (https://github.com/sequentech/strand/issues/72)
- [ ] Zeroization (https://docs.rs/zeroize/latest/zeroize/)
- [ ] Ensure that mixnet boards are never inserted with explicit ids (https://github.com/sequentech/backend-services/issues/33 https://github.com/sequentech/meta/issues/303)
- [ ] Include voter pseudonym (or signing pk) in popk context when casting vote
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
