### ISSUE TITLE
✨ Tally only of ENABLED voter votes

### ISSUE THREAD

**Issue by lnabergoi** [sequentech/step#473]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Expected

Tally only of ENABLED voter votes

### Environment

- **Web browser**: Google Chrome 112.0.5615.137 (Official Build) (arm64)
- **Sequent Platform Version**: 10.2.0

### Tasks

```[tasklist]
# Tasks
- [x] Only tally enabled voters.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/475
```
